<a href="https://colab.research.google.com/github/Irfanazhari1/label-1/blob/main/Copy_of_cropping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!wget https://www.dropbox.com/s/xg78kiae02d4u8f/Conan.jpg --no-check-certificate

--2021-11-09 13:07:28--  https://www.dropbox.com/s/xg78kiae02d4u8f/Conan.jpg
Resolving www.dropbox.com (www.dropbox.com)... 162.125.2.18, 2620:100:601d:18::a27d:512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.2.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/xg78kiae02d4u8f/Conan.jpg [following]
--2021-11-09 13:07:28--  https://www.dropbox.com/s/raw/xg78kiae02d4u8f/Conan.jpg
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc8670d6da6319d20db705fecf4f.dl.dropboxusercontent.com/cd/0/inline/BZqmv1CcZKK9CY8zKnnPGHA9f6H5xKOhWaWKTDN6jNSwEgXA0gYYDesMMpkpALZFQSlx6BkTLhPSTwMUHYxjceHT8ZWI6BApFuqI80qov0Vl1WbPVa8D4qCGu9KcCh0vcS_VMAAx_Qyai1U5YchQZHnb/file# [following]
--2021-11-09 13:07:28--  https://uc8670d6da6319d20db705fecf4f.dl.dropboxusercontent.com/cd/0/inline/BZqmv1CcZKK9CY8zKnnPGHA9f6H5xKOhWaWKTDN6jNSwEgXA0gYYDesMMpkpALZFQSlx6BkTLhPSTwMUHYxjceHT8ZWI6BApFuq

In [ ]:
# import the necessary packages
from matplotlib import pyplot as plt
import numpy as np
import argparse
import cv2

In [ ]:
def plt_imshow(title, image):
	# convert the image frame BGR to RGB color space and display it
	image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
	plt.imshow(image)
	plt.title(title)
	plt.grid(False)
	plt.show()

In [ ]:
I = np.arange(0, 25)
I

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
I = I.reshape((5, 5))
I

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
I[0:3, 0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [ ]:
I[3:5, 1:5]

array([[16, 17, 18, 19],
       [21, 22, 23, 24]])

In [2]:
# # construct the argument parser and parse the arguments
# ap = argparse.ArgumentParser()
# ap.add_argument("-i", "--image", type=str, default="adrian.png",
# 	help="path to the input image")
# args = vars(ap.parse_args())

# since we are using Jupyter Notebooks we can replace our argument
# parsing code with *hard coded* arguments and values
args = {
	"image": "Conan.jpg"
}

In [ ]:
# load the input image and display it to our screen
image = cv2.imread(args["image"])
plt_imshow("Original", image)

# cropping an image with OpenCV is accomplished via simple NumPy
# array slices in startY:endY, startX:endX order -- here we are
# cropping the monitor from the image (these coordinates were
# determined using photo editing software such as Photoshop,
# GIMP, Paint, etc.)
# Dimension lab.jpeg = 720x1600
lab = image[100:550, 100:500]
plt_imshow("test", lab)